version: '3'

services:
  decision_trees_dev:
    build:
      context: .
    volumes:
      - ./public/index.html:/app/public/index.html
      - ./src:/app/src
    env_file:
      - ./.env
    ports:
      - "4000:3000"
    tty: true
