version: '3'

services:
  decision_trees_build:
    image: predictanalyse/tree-decision-creator-front:latest
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    env_file:
      - ./.env
