version: '3'
services:
  decision_trees:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    tty: true
