# Stage 1 - the build process
FROM node:12-alpine3.11 as build-deps

LABEL MAINTAINER="Rami sfari <rami2sfari@gmail.com>"

# Copy project & set working directory
COPY . /app/
WORKDIR /app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV development

# install app dependencies
RUN ["npm", "install", "-f, --silence"]

RUN ["npm" , "build"]

# Stage 2 - the production environment
FROM nginx:1.17-alpine

COPY --from=build-deps /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
