export const ACTIONS = {
  FETCH_NODES_INIT: "FETCH_NODES_INIT",
  FETCH_NODES_SUCCEDED: "FETCH_NODES_SUCCEDED",
  FETCH_NODES_FAILED: "FETCH_NODES_FAILED",
  
  DELETE_NODE_INIT: "DELETE_NODE_INIT",
  DELETE_NODE_SUCCEDED: "DELETE_NODE_SUCCEDED",
  DELETE_NODE_FAILED: "DELETE_NODE_FAILED",

  FETCH_ALL_SCORES_INIT: "FETCH_ALL_SCORES_INIT",
  FETCH_ALL_SCORES_SUCCEDED: "FETCH_ALL_SCORES_SUCCEDED",
  FETCH_ALL_SCORES_FAILED: "FETCH_ALL_SCORES_FAILED",

  FETCH_ALL_NODES_INIT: "FETCH_ALL_NODES_INIT",
  FETCH_ALL_NODES_SUCCEDED: "FETCH_ALL_NODES_SUCCEDED",
  FETCH_ALL_NODES_FAILED: "FETCH_ALL_NODES_FAILED",

  CLEAR_NODE_FORM: "CLEAR_NODE_FORM",

  CREATE_NODE_INIT: "CREATE_NODE_INIT",
  CREATE_NODE_SUCCEDED: "CREATE_NODE_SUCCEDED",
  CREATE_NODE_FAILED: "CREATE_NODE_FAILED",

  FETCH_NODE_INIT: "FETCH_NODE_INIT",
  FETCH_NODE_SUCCEDED: "FETCH_NODE_SUCCEDED",
  FETCH_NODE_FAILED: "FETCH_NODE_FAILED",

  EDIT_NODE_INIT: "EDIT_NODE_INIT",
  EDIT_NODE_SUCCEDED: "EDIT_NODE_SUCCEDED",
  EDIT_NODE_FAILED: "EDIT_NODE_FAILED",

  FETCH_CURRENT_TREE_INIT: "FETCH_CURRENT_TREE_INIT",
  FETCH_CURRENT_TREE_SUCCEDED: "FETCH_CURRENT_TREE_SUCCEDED",
  FETCH_CURRENT_TREE_FAILED: "FETCH_CURRENT_TREE_FAILED",

  FILTER_NODES: "FILTER_NODES"
}

export const ENDPOINT = {
  TREE: "/api/tree/:param",
  NODES: "/api/tree/:treeparam/nodes",
  NODE: "/api/tree/:treeparam/node/:nodeparam",
  LOGIC_NODES: "/api/tree/:treeparam/node/logic",
  LOGIC_NODE: "/api/tree/:treeparam/node/logic/:nodeparam",
  CONTENT_NODES: "/api/tree/:treeparam/node/content",
  CONTENT_NODE: "/api/tree/:treeparam/node/content/:nodeparam",
  TREE_ALL_SCORE: "/api/tree/:treeparam/all/scores",
  TREE_ALL_NODES: "/api/tree/:treeparam/all/nodes"

}


export const NODE_TYPE = { CONTENT_NODE: "ContentNode", LOGIC_NODE: "LogicNode" }
