version: '2'

services:
  decision_tree_deploy:
    container_name: decision_tree_deploy
    image: predictanalyse/tree-decision-creator-front:latest
    env_file:
      - ./.env
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.decision_trees_front.tls=${TLS}
      - traefik.http.routers.decision_trees_front.rule=Host("${SITE_DOMAINE_NAME}")
      - traefik.http.services.decision_tree_front_service.loadbalancer.server.port=8080

networks:
  traefik:
    external: true
