export const ACTIONS = {
  FETCH_NODES_INIT: "FETCH_NODES_INIT",
  FETCH_NODES_SUCCEDED: "FETCH_NODES_SUCCEDED",
  FETCH_NODES_FAILED: "FETCH_NODES_FAILED",
  
  DELETE_NODE_INIT: "DELETE_NODE_INIT",
  DELETE_NODE_SUCCEDED: "DELETE_NODE_SUCCEDED",
  DELETE_NODE_FAILED: "DELETE_NODE_FAILED"
}

export const ENDPOINT = {
  NODES: "/api/tree/:treeparam/nodes",
  NODE: "/api/tree/:treeparam/node/:param",
}
