export const ACTIONS = {
  FETCH_ALL_SCORES_INIT: "FETCH_ALL_SCORES_INIT",
  FETCH_ALL_SCORES_SUCCEDED: "FETCH_ALL_SCORES_SUCCEDED",
  FETCH_ALL_SCORES_FAILED: "FETCH_ALL_SCORES_FAILED",

  FETCH_ALL_NODES_INIT: "FETCH_ALL_NODES_INIT",
  FETCH_ALL_NODES_SUCCEDED: "FETCH_ALL_NODES_SUCCEDED",
  FETCH_ALL_NODES_FAILED: "FETCH_ALL_NODES_FAILED",

  CLEAR_NODE_FORM: "CLEAR_NODE_FORM",

  CREATE_NODE_INIT: "CREATE_NODE_INIT",
  CREATE_NODE_SUCCEDED: "CREATE_NODE_SUCCEDED",
  CREATE_NODE_FAILED: "CREATE_NODE_FAILED",

  FETCH_NODE_INIT: "FETCH_NODE_INIT",
  FETCH_NODE_SUCCEDED: "FETCH_NODE_SUCCEDED",
  FETCH_NODE_FAILED: "FETCH_NODE_FAILED",

  EDIT_NODE_INIT: "EDIT_NODE_INIT",
  EDIT_NODE_SUCCEDED: "EDIT_NODE_SUCCEDED",
  EDIT_NODE_FAILED: "EDIT_NODE_FAILED",
}

export const ENDPOINT = {
  NODES: "/api/tree/:treeparam/node/logic",
  NODE: "/api/tree/:treeparam/node/logic/:nodeparam",
  TREE_ALL_SCORE: "/api/tree/:treeparam/all/scores",
  TREE_ALL_NODES: "/api/tree/:treeparam/all/nodes"
}
